"""Manual static build. Python standard library only; no network or automation."""
from pathlib import Path
from html import escape as e
import json

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://cryptographicdiscovery.com'
DATE = '2026-09-22'
DISCLAIMER = 'Independent editorial reference. No affiliation with NIST, NCCoE, NSA, ANSSI, ENISA, OWASP, or any standards body, regulatory authority, or certification organization. Not a standard, certification, or compliance scheme. Does not constitute legal, regulatory, financial, or security advice. Research assisted by AI tools, reviewed and validated before publication. Editorial responsibility: XB2 EURL, RCS Bayonne 922 532 320, France. All rights reserved; quotation with attribution and link welcome.'
records = json.loads((ROOT / 'data/records.json').read_text())
records.sort(key=lambda r: r['name'].casefold())
DEFINITION = 'Cryptographic discovery identifies where and how cryptography is used in software, systems and services.'
NCCOE = 'https://www.nccoe.nist.gov/applied-cryptography/migration-to-pqc'
CBOM = 'https://cyclonedx.org/guides/OWASP_CycloneDX-Authoritative-Guide-to-CBOM-en.pdf'

def link(url, label):
    return f'<a href="{e(url, quote=True)}">{e(label)}</a>'

def page(path, title, description, body, active='', schema=None):
    nav = ''.join(f'<a href="{url}"'+(' aria-current="page"' if active == name else '')+f'>{name}</a>' for name, url in [('Index','/'),('Editorial policy','/editorial-policy'),('Contact','/contact')])
    canonical = BASE + ('/' if path == 'index.html' else '/' + path.removesuffix('.html'))
    ld = '<script type="application/ld+json">'+json.dumps(schema, ensure_ascii=False).replace('</','<\\/')+'</script>' if schema else ''
    noindex = '<meta name="robots" content="noindex">' if path == '404.html' else ''
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)} · CDRI</title><meta name="description" content="{e(description, quote=True)}">{noindex}
<link rel="canonical" href="{canonical}"><meta property="og:title" content="{e(title, quote=True)} · CDRI"><meta property="og:description" content="{e(description, quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}">
<meta name="theme-color" content="#163e38"><link rel="icon" href="/assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css">{ld}
</head><body><a class="skip" href="#main">Skip to content</a>
<header class="site-header wrap"><a class="brand" href="/" aria-label="CDRI home"><span class="mark" aria-hidden="true">c<span>·</span>d</span><span><strong>CDRI</strong><small>Cryptographic Discovery<br>Reference Index</small></span></a><nav aria-label="Main navigation">{nav}</nav></header>
<main id="main" class="wrap">{body}</main>
<footer class="wrap site-footer"><div class="footer-heading"><strong>CDRI <span>/ Independent editorial reference</span></strong><a href="/contact">Corrections &amp; contact ↗</a></div><p class="disclaimer">{DISCLAIMER}</p><p class="publisher">Published by XB2 EURL, RCS Bayonne 922 532 320, France. Contact: <a href="mailto:contact@cryptographicdiscovery.com">contact@cryptographicdiscovery.com</a></p></footer>
{'<script src="/assets/index.js" defer></script>' if active == 'Index' else ''}</body></html>'''
    (ROOT / path).write_text(html)

def record(r):
    fields = [('Type',r['type']),('Method',r['method']),('Output format',r['output']),('Status',r['status']),('Source version / date',r['version']),('Last checked',r['checked'])]
    dl = ''.join(f'<div><dt>{e(k)}</dt><dd>{e(v)}</dd></div>' for k,v in fields)
    sources = ''.join('<li>'+link(s['url'],s['label'])+' <span aria-hidden="true">↗</span></li>' for s in r['sources'])
    search = e(' '.join([r[k] for k in ['name','scope','type','method','output','status']]), quote=True)
    return f'''<details class="record" id="{r['id']}" data-type="{r['type']}" data-method="{r['method']}" data-search="{search}"><summary><span class="record-name"><strong>{e(r['name'])}</strong><span>{e(r['scope'])}</span></span><span class="record-labels"><span class="type-tag">{r['type']}</span><span class="method-tag">{r['method']}</span></span><span class="expander" aria-hidden="true"></span></summary><div class="record-body"><dl class="fields">{dl}</dl><div class="source-box"><h3>Primary sources</h3><ul>{sources}</ul><p class="note">{e(r['note'])}</p><a class="permalink" href="/#{r['id']}">Link to this record <span aria-hidden="true">↗</span></a></div></div></details>'''

intro = f'''<section class="intro"><p class="eyebrow">Independent reference · Edition 01</p><h1>Find the source.<br><em>Understand the scope.</em></h1><div class="intro-bottom"><p>An editorial index of cryptographic discovery tools, formats and public references. Documented facts, linked to their primary sources.</p><a class="text-link" href="#index">Explore the {len(records)} records <span aria-hidden="true">↓</span></a></div></section>
<section class="definition" aria-labelledby="definition-title"><div class="definition-top"><p class="eyebrow light">The starting point</p><h2 id="definition-title">What is cryptographic discovery?</h2><p id="definition">{DEFINITION}</p><p class="source-caption">Editorial synthesis based on {link(NCCOE,'NCCoE’s migration project')}.</p></div><ol class="pathway"><li><span class="step">01 / DISCOVERY</span><h3>Observe</h3><p>Identify cryptographic assets and their use within the scope of an observation.</p></li><li><span class="step">02 / INVENTORY</span><h3>Organise</h3><p>Bring findings together with context and relationships. Keep the observation scope and date.</p></li><li><span class="step">03 / CBOM</span><h3>Represent</h3><p>Describe cryptographic assets and dependencies in a machine-readable model, such as CycloneDX CBOM.</p></li></ol><p class="pathway-note">Discovery → inventory → CBOM is an editorial explanation of the relationship, not a prescribed process. A CBOM does not by itself establish complete discovery coverage. Sources: {link(NCCOE,'NCCoE')} · {link(CBOM,'CycloneDX CBOM guide')}.</p></section>
<section id="index" class="catalog" aria-labelledby="index-title"><div class="section-heading"><div><p class="eyebrow">The reference index</p><h2 id="index-title">Tools, formats &amp; guidance</h2></div><p class="edition-date">{len(records)} records · A–Z<br>Source checks: 22 September 2026</p></div><p class="catalog-intro">Open a record for its scope, output, status and sources. Inclusion is not endorsement; the index is a selected starting set, not an exhaustive catalogue. <a href="/editorial-policy#field-guide">How to read these fields ↗</a></p>
<form id="filters" class="filters" role="search" hidden><label class="search-label" for="query">Search records<input id="query" type="search" placeholder="Name, scope or output…" autocomplete="off"></label><label for="type">Type<select id="type"><option value="">All types</option><option>open source</option><option>commercial</option><option>editorial</option></select></label><label for="method">Method<select id="method"><option value="">All methods</option><option>static</option><option>runtime</option><option>network</option><option>mixed</option><option>not applicable</option><option>not documented</option></select></label><button type="reset">Reset</button></form><p id="result-count" class="result-count" role="status" aria-live="polite" hidden></p><div class="records">{''.join(record(r) for r in records)}</div><p id="empty" class="empty" hidden>No records match these filters. Try a broader search or use Reset.</p><noscript><p>All records are available above. Open each record to read its fields and sources.</p></noscript></section>'''
schema = {'@context':'https://schema.org','@graph':[{'@type':'ItemList','@id':BASE+'/#index','name':'Cryptographic Discovery Reference Index','description':'An independent editorial index of cryptographic discovery tools, formats and primary reference publications.','url':BASE+'/','numberOfItems':len(records),'itemListOrder':'https://schema.org/ItemListOrderAscending','itemListElement':[{'@type':'ListItem','position':i+1,'item':{'@type':'Thing','@id':BASE+'/#'+r['id'],'name':r['name'],'description':r['scope'],'url':BASE+'/#'+r['id']}} for i,r in enumerate(records)]},{'@type':'DefinedTerm','@id':BASE+'/#definition','name':'Cryptographic discovery','description':DEFINITION,'url':BASE+'/#definition','subjectOf':{'@type':'WebPage','url':NCCOE,'name':'NCCoE Migration to Post-Quantum Cryptography'}}]}
page('index.html','Cryptographic Discovery Reference Index','Primary-source records on cryptographic discovery: documented scope, methods, output formats and source status. No scoring or ranking.',intro,'Index',schema)

policy = '''<section class="page-title"><p class="eyebrow">About this reference</p><h1>Editorial policy</h1><p class="lead">A clear trail from each factual record to its source.</p></section><div class="article-layout"><aside><p class="eyebrow">On this page</p><a href="#purpose">Purpose</a><a href="#sources">Sources &amp; selection</a><a href="#field-guide">Field guide</a><a href="#updates">Updates &amp; corrections</a><a href="#rights">Rights &amp; attribution</a></aside><article class="prose">
<section id="purpose"><h2>Purpose and boundaries</h2><p>CDRI is an independent editorial reference for locating and reading primary material about cryptographic discovery. It is neither a standard nor a framework. Records do not award scores, rank products or attest to security, compliance or fitness for a particular use.</p><p>The initial selection brings together public guidance, a representation format and documented discovery tools. It is not exhaustive and has no preferred vendor. Alphabetical order is for navigation only.</p><h3>Where CDRI fits</h3><p><a href="/#nist-sp-1800-38b">NCCoE’s work</a> documents example discovery architectures; <a href="/#nist-cswp-48">CSWP 48</a> maps project capabilities to NIST resources. <a href="/#cisa-strategy">CISA’s publication</a> concerns automated discovery and inventory. <a href="/#ncsc-migration">NCSC guidance</a> and <a href="/#etsi-tr-104016">ETSI’s report</a> address the wider migration process. <a href="/#cyclonedx-cbom">CycloneDX</a> provides a model for representing cryptographic assets.</p><p>CDRI adds a common reading surface: source, scope, observation method, output and publication status, with uncertainties made explicit. It does not replace these initiatives or claim their endorsement.</p></section>
<section id="sources"><h2>Sources and selection</h2><p>Records use primary sources only: issuing bodies, project maintainers and vendors’ own documentation. Publisher-maintained package descriptions can be used for open-source software. News coverage, reseller copy and unsourced aggregations are not evidence for record claims.</p><p>Technical capabilities are reported as documented by their source. CDRI has not executed or benchmarked the listed tools. A source check confirms support for the limited facts recorded here; it is not validation of product performance.</p><p>Each record identifies its source version or date where available and the date of the editorial check. A dated project description is not treated as a current software release. Where only an indexed primary excerpt was accessible, the record explicitly limits what was checked.</p><p>A relevant tool or publication may be included if its identity, scope and primary source can be established. Missing information is left unfilled using the field conventions below. Corrections require the same source discipline as new records.</p></section>
<section id="field-guide"><h2>How to read the fields</h2><h3>Type</h3><dl class="glossary"><div><dt>open source</dt><dd>Software identified as open source by its primary project or publisher source. Its own licence applies.</dd></div><div><dt>commercial</dt><dd>A vendor product. This label does not imply a particular price or licensing model.</dd></div><div><dt>editorial</dt><dd>A reference document, guidance publication or specification. This is CDRI’s content category, not a claim that the source is authored by CDRI.</dd></div></dl><h3>Method</h3><dl class="glossary"><div><dt>static</dt><dd>Inspection of source code, files or images without observing the target executing.</dd></div><div><dt>runtime</dt><dd>Observation of cryptographic use during execution.</dd></div><div><dt>network</dt><dd>Observation through network traffic or connections to exposed services.</dd></div><div><dt>mixed</dt><dd>Multiple observation approaches explicitly described by the source.</dd></div></dl><p>These are editorial descriptors of documented collection scope, not a technical standard. They are not applied to a publication as though the document were itself a scanner.</p><h3>Status</h3><dl class="glossary"><div><dt>draft</dt><dd>The cited source explicitly identifies the publication as a draft.</dd></div><div><dt>standard</dt><dd>The record concerns a published specification recognised as a standard by its issuing body.</dd></div><div><dt>open</dt><dd>The record concerns an open-source software project. It is not a maturity or quality grade.</dd></div><div><dt>in force</dt><dd>Reserved for an instrument whose applicability and effective status are explicitly established by its issuing source. Not assigned to tools or ordinary guidance.</dd></div></dl><p>Status labels describe different kinds of source; they are not a scale. A published technical report or a commercial product can legitimately have “not applicable” as its status.</p><h3>Missing and inapplicable information</h3><dl class="glossary"><div><dt>not applicable</dt><dd>The field does not fit the kind of record, such as a scanner method for a reference document.</dd></div><div><dt>not documented</dt><dd>The checked source does not establish the requested fact. This does not mean the capability is absent.</dd></div></dl><p>“Output format” describes the documented discovery or inventory output, not the PDF or HTML format of a reference publication. When a source mentions a CBOM but does not identify its serialization, that limit is retained.</p></section>
<section id="updates"><h2>Updates and corrections</h2><p>The initial maintenance cycle is a manual weekly review. The editor checks source changes, versions, links and status, then revises affected records. The last-checked date changes only when a source has actually been reviewed; it is not automatically refreshed.</p><p>Material changes receive a dated note in the revision history. Source outages or conflicting documentation are recorded rather than silently resolved by inference. A missed review leaves the previous date visible.</p><p>To suggest a correction, send the record link, the disputed field and a primary source through <a href="/contact">Contact</a>. Suggestions do not automatically change a record.</p><h3>Revision history</h3><p><time datetime="2026-09-22">22 September 2026</time> — Initial set of 12 source-checked records prepared for editorial approval. CISA is a metadata-only record; the IBM Explorer record uses indexed primary documentation, with access limits disclosed.</p></section>
<section id="rights"><h2>Rights and attribution</h2><p>All rights reserved. Quotation with attribution to CDRI and a link to the relevant record is welcome. This site is not offered under a Creative Commons licence. Referenced publications, trademarks and software retain their respective owners’ rights and licences.</p><p>Suggested attribution: “CDRI — Cryptographic Discovery Reference Index, [record name], [record link], accessed [date].”</p></section></article></div>'''
page('editorial-policy.html','Editorial policy','Source selection, factual field definitions, manual review policy and attribution terms for CDRI.',policy,'Editorial policy')
contact = '''<section class="page-title"><p class="eyebrow">Get in touch</p><h1>Contact</h1><p class="lead">Corrections, primary sources and editorial enquiries.</p></section><div class="contact-grid"><section class="contact-card"><h2>Write to the editor</h2><a class="email" href="mailto:contact@cryptographicdiscovery.com">contact@cryptographicdiscovery.com <span aria-hidden="true">↗</span></a><p>For a correction, include the record link, the field to review and a primary source supporting the change.</p><p>Please do not send passwords, private keys or confidential inventories. This index does not receive or analyse your systems.</p></section><section class="publisher-card"><p class="eyebrow">Publisher</p><h2>XB2 EURL</h2><p>RCS Bayonne 922 532 320<br>France</p><p>Editorial responsibility: XB2.</p><a href="/editorial-policy">Read the editorial policy ↗</a></section></div><section class="availability"><h2>Domain enquiries</h2><p>The domain cryptographicdiscovery.com is available for acquisition. Enquiries may be sent to the contact address above.</p></section>'''
page('contact.html','Contact','Contact XB2 EURL about CDRI records, corrections and primary sources.',contact,'Contact')
page('404.html','Page not found','This page could not be found.', '<section class="page-title"><p class="eyebrow">404</p><h1>Page not found.</h1><p class="lead">The reference index has moved on. Find the current records below.</p><a class="text-link" href="/">Return to the index →</a></section>')
(ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}{p}</loc></url>' for p in ['/','/editorial-policy','/contact'])+'</urlset>\n')
(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'/sitemap.xml\n')
print(f'Built index with {len(records)} records, editorial policy, contact, 404 and sitemap.')
